import { Provider } from "./components/ui/provider"
import localFont from 'next/font/local'
import { Playfair_Display } from 'next/font/google'
import { Header } from "./components/Header"
import { Footer } from "./components/Footer"
import './globals.css'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: './fonts/MADETommySoft.otf',
  display: 'swap',
  weight: '400',
  style: 'normal',
});

const playfair = Playfair_Display({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.className} ${myFont.className}`} suppressHydrationWarning>
      <body>
        <Provider>
          <Header />
          <main>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
