import { Provider } from "./components/ui/provider";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Playfair_Display } from "next/font/google";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { Toaster } from "./components/ui/toaster";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: "./fonts/MADETommySoft.otf",
  display: "swap",
  weight: "400",
  style: "normal",
});

const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages(locale);
  return (
    <html
      lang={locale}
      className={`${playfair.className} ${myFont.className}`}
      suppressHydrationWarning
    >
      <body>
        <Provider>
          <NextIntlClientProvider messages={messages}>
            <Header />
            <main>{children}<Toaster/></main>
            <Footer />
          </NextIntlClientProvider>
        </Provider>
      </body>
    </html>
  );
}
